### ISSUE TITLE
Error: No normalization

### ISSUE THREAD

**Issue by Jorges1000** [bm2-lab/SpaDo#1]
Hello,

Trying to run either `InitialClustering` or `SpatialCellTypeDistribution` with Seurat v5:

`Error in `ScaleData()`:
! No layer matching pattern 'data' found. Please run NormalizeData and retry`

The problem can be fixed by adding NormalizeData:

```
sce_seurat <- FindVariableFeatures(sce_seurat, nfeatures = nfeatures)  
sce_seurat <- NormalizeData(sce_seurat) ## Added  
sce_seurat <- ScaleData(sce_seurat)
```

**Comment by BinDuan** [comment]
> Hello,
> 
> Trying to run either `InitialClustering` or `SpatialCellTypeDistribution` with Seurat v5:
> 
> `Error in `ScaleData()`: ! No layer matching pattern 'data' found. Please run NormalizeData and retry`
> 
> The problem can be fixed by adding NormalizeData:
> 
> ```
> sce_seurat <- FindVariableFeatures(sce_seurat, nfeatures = nfeatures)  
> sce_seurat <- NormalizeData(sce_seurat) ## Added  
> sce_seurat <- ScaleData(sce_seurat)
> ```

Thank you for using SpaDo. SpaDo made its own normalization step instead of that in Seurat. We don't recommend to add "sce_seurat <- NormalizeData(sce_seurat)" which may affect the performance of SpaDo. SpaDo was originally built on Seurat 4.0.4 and SeuratObject 4.0.4  instead of Seurat v5.

**Comment by ShweiSTAT** [comment]
Hi BinDuan, 

I think I ran into a similar problem as well. I tried to install Seurat 4.0.4 on my computer but there is always an error message stopping the installation. I published an issue on Seurat's GitHub as well, please refer to https://github.com/satijalab/seurat/issues/9185. 

I wonder if I can request an update on SpaDO to make it compatible with the latest Seurat, since the older version of Seurat depends on a deprecated package named "spatstat.core", which might cause an issue on the installing. 

Thank you so much!

**Comment by ShweiSTAT** [comment]
Right now I have Seurat 5.1.0, SeuratObject 5.0.2. When I was running the tutorial code for the multiple slices example (Example 5), I have these error messages: 

load("./test_Data_spDo/TLS_all_slices.RData")
cell_type_distribution_multiple<-SpatialCellTypeDistribution_multiple(sample_information_coordinate_list = coordinate_list,
                                                                      sequence_resolution = 'spot',
                                                                      sample_information_decon_list = decon_list)

<img width="616" alt="Screenshot 2024-08-05 at 5 55 40 PM" src="https://github.com/user-attachments/assets/9b9205e2-1a43-46ee-a433-d76e7abb7ad3">

I wonder if u know how to fix this.

Thanks!

**Comment by BinDuan** [comment]
> Hi BinDuan,
> 
> I think I ran into a similar problem as well. I tried to install Seurat 4.0.4 on my computer but there is always an error message stopping the installation. I published an issue on Seurat's GitHub as well, please refer to [satijalab/seurat#9185](https://github.com/satijalab/seurat/issues/9185).
> 
> I wonder if I can request an update on SpaDO to make it compatible with the latest Seurat, since the older version of Seurat depends on a deprecated package named "spatstat.core", which might cause an issue on the installing.
> 
> Thank you so much!

We recently updated SpaDo with two improvements: (1) Ensuring compatibility with Seurat v5 in the "InitialClustering" function; (2) Enabling parallel execution for the "DistributionDistance" function when using the "JSD" distance metric, significantly reducing runtime. Now you can reinstall SpaDo and try it again with Seurat v5.

**Comment by ShweiSTAT** [comment]
Thx for your quick reply. I tried to reinstall SpaDo by this code: 
install_github("bm2-lab/SpaDo")

I still have the same error message when running "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple". The SpaDo that I have redownloaded is 1.0 .

**Comment by BinDuan** [comment]
> Thx for your quick reply. I tried to reinstall SpaDo by this code: install_github("bm2-lab/SpaDo")
> 
> I still have the same error message when running "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple". The SpaDo that I have redownloaded is 1.0 .

Sorry for this problem, I forgot to update "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple". Now we updated SpaDo again especially for "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple" in SpaDo v1.2.0. You can reinstall SpaDo or just use the revised "SpatialCellTypeDistribution" shown below:

SpatialCellTypeDistribution<-SpatialCellTypeDistribution<-function (sample_information_coordinate, sequence_resolution = c("single_cell", 
    "spot"), sample_information_cellType = NULL, sample_information_decon = NULL, 
    neighbour_search_method = (ifelse(sequence_resolution == 
        "single_cell", "KNN", "radius")), k = (ifelse(neighbour_search_method == 
        "KNN", 30, FALSE)), r = (ifelse(neighbour_search_method == "radius", 2, FALSE))) 
{
    SpatialKNN <- function(sample_information_coordinate) {
        require(Seurat)
        test_coordinate <- sample_information_coordinate
        test_coordinate_expand <- test_coordinate
        for (i in 1:5) {
            test_coordinate_expand <- cbind(test_coordinate, 
                test_coordinate_expand)
        }
        colnames(test_coordinate_expand) <- paste(colnames(test_coordinate_expand), 
            1:ncol(test_coordinate_expand))
        sce_seurat <- CreateSeuratObject(t(test_coordinate_expand))
        ### To ensure compatibility with Seurat v5, we manually added the data layer.
        sce_seurat@assays$RNA@data<-sce_seurat@assays$RNA@counts
        sce_seurat <- ScaleData(sce_seurat)
        sce_seurat <- RunPCA(sce_seurat, features = rownames(sce_seurat), 
            ndims.print = 1, nfeatures.print = 1, npcs = 5)
        sce_seurat@reductions$pca@cell.embeddings <- as.matrix(test_coordinate)
        sce_seurat <- FindNeighbors(sce_seurat, reduction = "pca", 
            dims = 1:2, return.neighbor = T, k.param = 50)
        knn_sample <- sce_seurat@neighbors$RNA.nn@nn.idx
        knn_value <- sce_seurat@neighbors$RNA.nn@nn.dist
        cell_names <- sce_seurat@neighbors$RNA.nn@cell.names
        row.names(knn_sample) <- cell_names
        row.names(knn_value) <- cell_names
        knn_sample <- t(apply(knn_sample, 1, function(x, y) {
            y <- cell_names
            return(y[x])
        }))
        return(list(knn_value = knn_value, knn_sample = knn_sample))
    }
    SpatialKNN_result <- SpatialKNN(sample_information_coordinate)
    require(reshape2)
    neighbour_search_method = neighbour_search_method[1]
    knn_sample <- SpatialKNN_result$knn_sample
    knn_value <- SpatialKNN_result$knn_value
    knn_choose <- list()
    if (neighbour_search_method == "KNN") {
        if (k < 2) {
            print("k must be bigger than 1")
            break
        }
        for (i in 1:nrow(knn_sample)) {
            knn_choose[[i]] <- knn_sample[i, 1:k]
        }
    }
    else if (neighbour_search_method == "radius") {
        for (i in 1:nrow(knn_sample)) {
            knn_choose[[i]] <- knn_sample[i, knn_value[i, ] <= 
                r]
        }
    }
    else {
        print("Parameter 'neighbour_search_method' must be 'KNN' or 'radius'!")
        break
    }
    names(knn_choose) <- row.names(knn_sample)
    knn_choose_cellType <- knn_choose
    sequence_resolution <- sequence_resolution[1]
    if (sequence_resolution == "single_cell") {
        names(knn_choose_cellType) <- sample_information_cellType[names(knn_choose)]
        for (i in 1:length(knn_choose_cellType)) {
            knn_choose_cellType[[i]] <- sample_information_cellType[knn_choose[[i]]]
        }
        cellType_names <- names(table(sample_information_cellType))
        knn_matrix_list <- list()
        knn_matrix_cellType_list <- list()
        for (i in 1:length(cellType_names)) {
            knn_matrix_cellType <- knn_choose_cellType[names(knn_choose_cellType) == 
                cellType_names[i]]
            knn_matrix <- knn_choose[names(knn_choose_cellType) == 
                cellType_names[i]]
            knn_matrix_list[[i]] <- knn_matrix
            knn_matrix_cellType_list[[i]] <- knn_matrix_cellType
        }
        names(knn_matrix_list) <- cellType_names
        names(knn_matrix_cellType_list) <- cellType_names
        knn_matrix <- list(knn_matrix_cellType_list = knn_matrix_cellType_list, 
            knn_matrix_list = knn_matrix_list)
        cellType_names <- names(table(sample_information_cellType))
        cell_type_distribution_each_list <- list()
        cell_type_distribution <- matrix(NA, 0, length(cellType_names))
        colnames(cell_type_distribution) <- cellType_names
        cell_type_distribution_rownames <- c()
        for (k in 1:length(cellType_names)) {
            test_cellType_matrix <- knn_matrix[[1]][[k]]
            test_matrix <- knn_matrix[[2]][[k]]
            cell_type_distribution_rownames <- c(cell_type_distribution_rownames, 
                names(test_matrix))
            cell_type_distribution_each <- matrix(0, length(test_cellType_matrix), 
                length(cellType_names))
            colnames(cell_type_distribution_each) <- cellType_names
            for (i in 1:length(test_cellType_matrix)) {
                cellType_table <- table(factor(test_cellType_matrix[[i]], 
                  levels = cellType_names))
                if (sum(cellType_table) == 0) {
                  cell_type_distribution_each[i, ] <- cellType_table
                }
                else {
                  cell_type_distribution_each[i, ] <- cellType_table/sum(cellType_table)
                }
            }
            row.names(cell_type_distribution_each) <- names(test_matrix)
            cell_type_distribution_each_list[[k]] <- cell_type_distribution_each
            cell_type_distribution <- rbind(cell_type_distribution, 
                cell_type_distribution_each)
        }
        names(cell_type_distribution_each_list) <- cellType_names
        row.names(cell_type_distribution) <- cell_type_distribution_rownames
        return(cell_type_distribution)
    }
    else if (sequence_resolution == "spot") {
        sample_information_cellType <- rep(c("a", "b", "c","d","e"), 
            length.out = nrow(sample_information_decon))
        names(sample_information_cellType) <- row.names(sample_information_decon)
        names(knn_choose_cellType) <- sample_information_cellType[names(knn_choose)]
        for (i in 1:length(knn_choose_cellType)) {
            knn_choose_cellType[[i]] <- sample_information_cellType[knn_choose[[i]]]
        }
        cellType_names <- names(table(sample_information_cellType))
        knn_matrix_list <- list()
        knn_matrix_cellType_list <- list()
        for (i in 1:length(cellType_names)) {
            knn_matrix_cellType <- knn_choose_cellType[names(knn_choose_cellType) == 
                cellType_names[i]]
            knn_matrix <- knn_choose[names(knn_choose_cellType) == 
                cellType_names[i]]
            knn_matrix_list[[i]] <- knn_matrix
            knn_matrix_cellType_list[[i]] <- knn_matrix_cellType
        }
        names(knn_matrix_list) <- cellType_names
        names(knn_matrix_cellType_list) <- cellType_names
        knn_matrix <- list(knn_matrix_cellType_list = knn_matrix_cellType_list, 
            knn_matrix_list = knn_matrix_list)
        cellType_names <- colnames(sample_information_decon)
        cell_type_distribution <- matrix(NA, 0, length(cellType_names))
        colnames(cell_type_distribution) <- cellType_names
        cell_type_distribution_rownames <- c()
        for (k in 1:length(knn_matrix[[2]])) {
            test_matrix <- knn_matrix[[2]][[k]]
            cell_type_distribution_rownames <- c(cell_type_distribution_rownames, 
                names(test_matrix))
            for (i in 1:length(test_matrix)) {
                if (length(test_matrix[[i]]) == 1) {
                  cell_type_distribution <- rbind(cell_type_distribution, 
                    sample_information_decon[test_matrix[[i]], 
                      ])
                }
                else {
                  cell_type_distribution <- rbind(cell_type_distribution, 
                    apply(sample_information_decon[test_matrix[[i]], 
                      ], 2, mean))
                }
            }
        }
        row.names(cell_type_distribution) <- cell_type_distribution_rownames
        return(cell_type_distribution)
    }
    else {
        print("sequence_resolution must be one of 'single_cell' and 'spot'!")
        break
    }
}

**Comment by ShweiSTAT** [comment]
Hi Thank you so much!

I tried both reinstalling SpaDo and the revised "SpatialCellTypeDistribution". I still had errors when running "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple." The error messages from this two functions are the same. They are:

<img width="503" alt="Screenshot 2024-08-07 at 6 12 06 PM" src="https://github.com/user-attachments/assets/54ae8f29-5b86-4817-baa7-82cc8823862a">

**Comment by BinDuan** [comment]
> Hi Thank you so much!
> 
> I tried both reinstalling SpaDo and the revised "SpatialCellTypeDistribution". I still had errors when running "SpatialCellTypeDistribution" and "SpatialCellTypeDistribution_multiple." The error messages from this two functions are the same. They are:
> <img alt="Screenshot 2024-08-07 at 6 12 06 PM" width="503" src="https://private-user-images.githubusercontent.com/123591955/356046777-54ae8f29-5b86-4817-baa7-82cc8823862a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxODYzNTIsIm5iZiI6MTcyMzE4NjA1MiwicGF0aCI6Ii8xMjM1OTE5NTUvMzU2MDQ2Nzc3LTU0YWU4ZjI5LTViODYtNDgxNy1iYWE3LTgyY2M4ODIzODYyYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwOVQwNjQ3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjU5YjQwY2Q5MDlkZmY2OTlkODg4ZGUyNWZlODhhYmUwMjAzMWQ0MGFjMjNmMzU1ZmZlMjE2NmYzNjE3MTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bf5By83SiTZB40QerZDD5DEFlo5lWbAbtTOZfdWSC7Q">

Sorry for this inconvenience. We recently updated SpaDo again and tested it carefully. Please reinstall SpaDo again and I hope it helps. 
(1) SpaDo was originally built on Seurat 4.0.4 and SeuratObject 4.0.4. To avoid problems due to Seurat updates, We recently (2024.8.9) updated SpaDo to ensure compatibility with Seurat v5;
(2) Enabling parallel execution for the "DistributionDistance" function when using the "JSD" distance metric, significantly reducing runtime;
(3) We updated corresponding tutorials.

**Comment by BinDuan** [comment]
> Hello,
> 
> Trying to run either `InitialClustering` or `SpatialCellTypeDistribution` with Seurat v5:
> 
> `Error in `ScaleData()`: ! No layer matching pattern 'data' found. Please run NormalizeData and retry`
> 
> The problem can be fixed by adding NormalizeData:
> 
> ```
> sce_seurat <- FindVariableFeatures(sce_seurat, nfeatures = nfeatures)  
> sce_seurat <- NormalizeData(sce_seurat) ## Added  
> sce_seurat <- ScaleData(sce_seurat)
> ```

Sorry for this inconvenience. We recently updated SpaDo again and tested it carefully. Please reinstall SpaDo again and I hope it helps.
(1) SpaDo was originally built on Seurat 4.0.4 and SeuratObject 4.0.4. To avoid problems due to Seurat updates, We recently (2024.8.9) updated SpaDo to ensure compatibility with Seurat v5;
(2) Enabling parallel execution for the "DistributionDistance" function when using the "JSD" distance metric, significantly reducing runtime;
(3) We updated corresponding tutorials.
