### ISSUE TITLE
 Bugs when integrated a large 10X Visium spatial RNA-seq data (total samples = 24, spots ≈ 60k) by using `DomainPlot_multiple`

### ISSUE THREAD

**Issue by NiklausZZZ** [bm2-lab/SpaDo#2]
Hi,
Thank you very much for developing such useful tools. When integrating a large spatial RNA-seq data (10X Visium,  total samples = 24, spots ≈ 60k), I encountered some bugs with `DomainPlot_multiple` function:

```R
> DomainPlot_multiple(domain_hclust = domain_hclust,
+                     distribution_distance = DD)
Loading required package: umap


 *** caught segfault ***
address 0x7f5874b53ec0, cause 'memory not mapped'

Traceback:
 1: metric.function(dT, i, neighbors)
 2: FUN(X[[i]], ...)
 3: lapply(seq_len(V), function(i) {    neighbors <- pick.random.k(i)    neighbor.distances <- metric.function(dT, i, neighbors)    result <- matrix(c(i, neighbors, -1, neighbor.distances),         ncol = 2)    result[order(result[, 2]), ]})
 4: knn.from.data(dT, k, metric.function, subsample.k)
 5: knn.from.data.reps(d, k, distfun, reps = config$knn_repeats)
 6: knn.info(d, config)
 7: implementations[[method]](d, config)
 8: umap(t(data))
 9: DrawCluster(t(distribution_distance), method = "umap", label = cluster_hc[row.names(distribution_distance)])
10: DomainPlot_multiple(domain_hclust = domain_hclust, distribution_distance = DD)

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
Selection: dev.off()
Selection: 1
R is aborting now ...
Segmentation fault (core dumped)
```

Any suggestions would be greatly appreciated!

**Comment by NiklausZZZ** [comment]
By the way, my server has 1 TB of free memory and 256 cpus.

**Comment by BinDuan** [comment]
Thank you for using SpaDo. I suspect the issue might be that the "DD" matrix is too large. Even though your server has ample memory, R might not be able to allocate such a large amount of memory to a single matrix. My suggestion is to replace "DD" with "cell_type_distribution_multiple$cell_type_distribution_combine," which will provide similar visualization results. Thank you for bringing this issue to my attention. I will include this tip in the tutorial in the future. I hope my response is helpful to you.

**Comment by BinDuan** [comment]
> By the way, my server has 1 TB of free memory and 256 cpus.

Now, we updated our tutorials by adding above tips to better visualize. I hope it works for you.

**Comment by NiklausZZZ** [comment]
Thanks!!!

**Comment by NiklausZZZ** [comment]
Sorry to bother! I encountered a new bug with `DomainHclust` function when I increased data sets (total up to ~80k spots):
```r
> domain_hclust<- DomainHclust(distribution_distance = DD, 
+                              autoselection = F,
+                              domain_num = 7
+                              )
Error in hclust(d = as.dist(distribution_distance), method = "ward.D2") : 
  size cannot be NA nor exceed 65536
```

Any suggestions would be greatly appreciated!

**Comment by BinDuan** [comment]
> Sorry to bother! I encountered a new bug with `DomainHclust` function when I increased data sets (total up to ~80k spots):
> 
> ```r
> > domain_hclust<- DomainHclust(distribution_distance = DD, 
> +                              autoselection = F,
> +                              domain_num = 7
> +                              )
> Error in hclust(d = as.dist(distribution_distance), method = "ward.D2") : 
>   size cannot be NA nor exceed 65536
> ```
> 
> Any suggestions would be greatly appreciated!

Thank for using spado. I checked this error message and found that this is limitation of stats::hclust. To overcome this, I replaced stats::hclust with fastcluster::hclust without anything else change in function "DomainHclust" of our spado package, and this problem is fixed! I updated spado package to solve this problem. You can reinstall spado or just install package "fastcluster" and rewrite function "DomainHclust" show below:

DomainHclust<-function (distribution_distance, autoselection = TRUE, auto_resolution = c(0, 
    1, 2, 3, 4), domain_num = 10) 
{
    ## fastcluster::hclust has faster speed than stats::hclust. 
    ## Besides, fastcluster::hclust is without the limitation that size cannot be NA nor exceed 65536
    library(fastcluster)
    result_hc <- fastcluster::hclust(d = as.dist(distribution_distance), method = "ward.D2")
    if (autoselection) {
        require(dynamicTreeCut)
        auto_resolution <- auto_resolution[1]
        cluster_hc_dy <- cutreeDynamic(result_hc, distM = distribution_distance, 
            deepSplit = auto_resolution)
        cluster_hc_dy_num <- length(table(cluster_hc_dy))
    }
    else {
        cluster_hc_dy_num = domain_num
    }
    cluster_hc_all = cutree(result_hc, k = 1:cluster_hc_dy_num)
    cluster_hc_all_order <- cluster_hc_all[result_hc$order, ]
    cluster_hc_all_order_rename <- as.data.frame(cluster_hc_all_order)
    colnames(cluster_hc_all_order_rename) <- paste("Domain_level", 
        1:cluster_hc_dy_num, sep = "_")
    cluster_hc_all_order_rename_c <- apply(cluster_hc_all_order_rename, 
        2, function(x) {
            return(as.character(x))
        })
    row.names(cluster_hc_all_order_rename_c) <- row.names(cluster_hc_all_order_rename)
    cluster_hc_all_order_rename_c <- as.data.frame(cluster_hc_all_order_rename_c)
    for (i in 1:ncol(cluster_hc_all_order_rename_c)) {
        cluster_hc_all_order_rename_c[, i] <- paste("Domain", 
            i, cluster_hc_all_order_rename_c[, i], sep = "_")
    }
    return(list(hclust_result_df = cluster_hc_all_order_rename_c, 
        hclust_result_model = result_hc, hclust_result_order = cluster_hc_all_order))
}

Thank you for bringing this issue to my attention. I hope it works for you.

**Comment by BinDuan** [comment]
By the way, fastcluster::hclust has the same clustering result as stats::hclust with only the speed is faster and without the limitation that size cannot be NA nor exceed 65536. Therefore, You can use it without any concerns.

**Comment by NiklausZZZ** [comment]
Many thanks!!! It is very helpful!
